title: <p align="center"> Mahalakshmi Bhat </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/Mahalakshmi Bhat/">LinkedIn</a> |
  <a href="https://milli2202.github.io/portfolio/">GitHub</a>
  
  <br>   
I am Milli working for SAP Labs. Currently working as senior Java Developer
  <br>
  </p>



theme: jekyll-theme-minimal
